=== iqb-berlin/testcenter/definitions/vo_Booklet.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="vo_Booklet"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

<xs:include schemaLocation="vo_Common.xsd"/>

  <!-- ###################################################################-->
  <xs:complexType name="UnitType">
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="label" type="xs:string" use="required"/>
    <xs:attribute name="labelshort" type="xs:string"/>
    <xs:attribute name="alias" type="xs:string"/>
  </xs:complexType>

  <!-- ###################################################################-->
  <xs:complexType name="TestletRestrictionsType">
    <xs:all>
      <xs:element name="TimeMax" type="ConfigType" minOccurs = "0" maxOccurs="1"/>
      <xs:element name="CodeToEnter" type="ConfigType" minOccurs = "0" maxOccurs="1"/>
      <xs:element name="Lock" type="ConfigType" minOccurs = "0" maxOccurs="1"/>
    </xs:all>
  </xs:complexType>

  <!-- ###################################################################-->
  <xs:group name="unitOrTestlet">
    <xs:choice>
      <xs:element name="Unit" type="UnitType" minOccurs = "1" maxOccurs="unbounded"/>
      <xs:element name="Testlet" type="TestletType" minOccurs = "1" maxOccurs="unbounded"/>
    </xs:choice>
  </xs:group>

  <!-- ###################################################################-->
  <xs:complexType name="TestletType">
    <xs:sequence>
      <xs:element name="Restrictions" type="TestletRestrictionsType" minOccurs="0" maxOccurs="1"/>
      <xs:choice>
        <xs:element name="Unit" type="UnitType" minOccurs = "1" maxOccurs="unbounded"/>
        <xs:group ref="unitOrTestlet" minOccurs = "1" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="label" type="xs:string" />
  </xs:complexType>

  <!-- ###################################################################-->
  <!-- ###################################################################-->

  <xs:element name="Booklet">
    <xs:complexType>
      <xs:all>
        <xs:element name="Metadata" type="MetadataType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="BookletConfig" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Config" type="KeyValueType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Units" type="TestletType" minOccurs="1" maxOccurs="1"/>
      </xs:all>
    </xs:complexType>
    <xs:unique name="BookletConfigKey">
      <xs:selector xpath="Config"/>
      <xs:field xpath="@key"/>
    </xs:unique>
  </xs:element>
</xs:schema>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_Config_value-1.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.0.0/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>CY-BkltConfigValue-1</Id>
		<Label>Test Bklt Configs value-1</Label>
		<Description>Testen der ersten Werte</Description>
	</Metadata>

	<BookletConfig>

		<!--its only important to navigated to the next page if page navibuttons are disabled -->
		<Config key="pagingMode">buttons</Config>
		
		<Config key="page_navibuttons">OFF</Config>
		<Config key="unit_menu">FULL</Config>
		<Config key="unit_navibuttons">OFF</Config>
		<Config key="force_presentation_complete">ON</Config>
		<Config key="force_response_complete">ON</Config>
		<Config key="unit_show_time_left">ON</Config>
		<Config key="unit_time_left_warnings">1</Config>
		<Config key="restore_current_page_on_return">ON</Config>
		<Config key="allow_player_to_terminate_test">OFF</Config>
		<Config key="lock_test_on_termination">ON</Config>
		<Config key="ask_for_fullscreen">ON</Config>
		<Config key="show_fullscreen_button">ON</Config>
		<Config key="unit_screenheader">WITH_UNIT_TITLE</Config>
		<Config key="unit_title">OFF</Config>
		

	</BookletConfig>

	<Units>

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
        <TimeMax minutes="2" leave = "confirm"/>
			</Restrictions>
			<Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="1"/>
      <Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="2"/>
		</Testlet>
		
		<Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="3"/>
	</Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/test-controller/CY_Bklt_TC-15.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/18.0.0-beta2/definitions/vo_Booklet.xsd">
  <Metadata>
    <Id>Cy-Bklt_TC-15</Id>
    <Label>Test-Controller-15</Label>
    <Description>Testheft Test-Controller 15</Description>
  </Metadata>

  <BookletConfig>
    <Config key="pagingMode">buttons</Config>
    <Config key="force_presentation_complete">OFF</Config>
    <Config key="force_response_complete">OFF</Config>
    <Config key="unit_menu">FULL</Config>
  </BookletConfig>

  <Units>

    <Testlet id="Tslt1" label="Aufgabenblock">
      <Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="1"/>
      <Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="2"/>
    </Testlet>

    <Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="3"/>
  </Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/test-controller/CY_Bklt_TC-4.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/18.0.0-beta/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>Cy-Bklt_TC-4</Id>
    <Label>Test-Controller-4</Label>
    <Description>Testheft Test-Controller 4</Description>
	</Metadata>

	<BookletConfig>
		<Config key="force_presentation_complete">OFF</Config>
		<Config key="force_response_complete">OFF</Config>
		<Config key="unit_show_time_left">ON</Config>
		<Config key="unit_menu">ON</Config>
		<Config key="lock_test_on_termination">ON</Config>
	</BookletConfig>

	<Units>
		<Unit id="CY-Unit.Sample-100" label="Startseite" labelshort="1" />

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
				<CodeToEnter code="Hase">Bitte gib das Freigabewort ein.</CodeToEnter>
				<TimeMax minutes="1"/>
			</Restrictions>
			<Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="2"/>
			<Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="3"/>
			<Unit id="CY-Unit.Sample-103" label="Aufgabe3" labelshort="4"/>
		</Testlet>

		<Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="5"/>
	</Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/aspect/booklet1.xml
<?xml version="1.0"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.4.1/definitions/vo_Booklet.xsd">
  <Metadata>
    <Id>booklet1</Id>
    <Label>Beispieltestheft 1</Label>
  </Metadata>
  <BookletConfig>
    <Config key="pagingMode">separate</Config>
    <Config key="page_navibuttons">SEPARATE_BOTTOM</Config>
    <Config key="unit_navibuttons">FULL</Config>
    <Config key="controller_design">2018</Config>
    <Config key="unit_screenheader">WITH_UNIT_TITLE</Config>
    <Config key="unit_title">ON</Config>
  </BookletConfig>
  <Units>
    <Unit id="testcenter-sample1" label="Beispiel-Unit 1" labelshort="1"/>
    <Testlet id="a_testlet_with_restrictions" label="First Block">
      <Restrictions>
        <CodeToEnter code="sample">Please insert the word `sample`.</CodeToEnter>
        <TimeMax minutes="1" />
      </Restrictions>
      <Unit id="testcenter-sample2" label="Beispiel-Unit 2" labelshort="2"/>
    </Testlet>
    <Unit id="testcenter-sample3" label="Beispiel-Unit 3" labelshort="3"/>
  </Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_Config_default.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.0.0/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>CY-BkltConfigDefaults</Id>
		<Label>Test Bklt Configs default</Label>
		<Description>Testen der Defaultwerte</Description>
	</Metadata>

	<BookletConfig>

		<!--its only important to navigated to the next page if page navibuttons are disabled -->
		<Config key="pagingMode">buttons</Config>

		<Config key="page_navibuttons">SEPARATE_BOTTOM</Config>
		<Config key="unit_menu">OFF</Config>
		<Config key="unit_navibuttons">FULL</Config>
		<Config key="force_presentation_complete">OFF</Config>
		<Config key="force_response_complete">OFF</Config>
		<Config key="unit_show_time_left">OFF</Config>
		<Config key="unit_time_left_warnings">1</Config>
		<Config key="restore_current_page_on_return">OFF</Config>
		<Config key="allow_player_to_terminate_test">ON</Config>
		<Config key="lock_test_on_termination">OFF</Config>
		<Config key="ask_for_fullscreen">OFF</Config>
		<Config key="show_fullscreen_button">OFF</Config>
		<Config key="unit_screenheader">EMPTY</Config>
		<Config key="unit_title">ON</Config>
		

	</BookletConfig>

	<Units>

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
        <TimeMax minutes="2" leave = "confirm"/>
			</Restrictions>
			<Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="1"/>
      <Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="2"/>
		</Testlet>

		<Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="3"/>
	</Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_Mode_RunHotRestart.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.0.0/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>CY-Bklt_runhotres</Id>
		<Label>Controller Mode: run-hot-restart</Label>
		<Description>Test f√ºr den Modus run-hot-restart</Description>
	</Metadata>

	<BookletConfig>
		<Config key="force_presentation_complete">OFF</Config>
		<Config key="force_response_complete">OFF</Config>
		<Config key="unit_show_time_left">ON</Config>
		<Config key="unit_menu">ON</Config>
		<Config key="lock_test_on_termination">ON</Config>
	</BookletConfig>

	<Units>
		<Unit id="CY-Unit.Sample-100" label="Startseite" labelshort="1" />

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
				<CodeToEnter code="Hase">Bitte gib das Freigabewort ein.</CodeToEnter>
				<TimeMax minutes="1"/>
				<DenyNavigationOnIncomplete presentation="ALWAYS" response="ALWAYS" />		
			</Restrictions>
			<Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="2"/>
			<Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="3"/>
			<Unit id="CY-Unit.Sample-103" label="Aufgabe3" labelshort="4"/>
		</Testlet>
		
		<Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="5"/>
	</Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/session-management/CY_Bklt_SM-1.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/18.0.0-beta2/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>Cy-Bklt_SM-1</Id>
		<Label>SM-1</Label>
		<Description>Testheft Session-Management 1</Description>
	</Metadata>

	<BookletConfig>
		<Config key="unit_show_time_left">OFF</Config>
		<Config key="unit_menu">OFF</Config>
	</BookletConfig>

	<Units>
		<Unit id="CY-Unit.Sample-100" label="Startseite" labelshort="1" />

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
				<CodeToEnter code="Hase">Bitte gib das Freigabewort ein.</CodeToEnter>
				<TimeMax minutes="1"/>
			</Restrictions>
			<Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="2"/>
			<Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="3"/>
			<Unit id="CY-Unit.Sample-103" label="Aufgabe3" labelshort="4"/>
		</Testlet>

		<Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="5"/>
	</Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_NavRestr_Bklt-0.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.4.0/definitions/vo_Booklet.xsd">
  <Metadata>
    <Id>CY-Bklt_NavRestrBklt-0</Id>
    <Label>check response-/presentation-complete from booklet-config OFF</Label>
  </Metadata>

  <BookletConfig>
    <!--its only important to navigated to the next page if page navibuttons are disabled -->
    <Config key="pagingMode">buttons</Config>
    <Config key="force_presentation_complete">OFF</Config>
    <Config key="force_response_complete">OFF</Config>
  </BookletConfig>

  <Units>
    <Unit id="CY-Unit.Sample-101" label="Start" labelshort="1" alias="start"/>

    <Testlet id="Tslt1" label="Aufgabenblock">
      <Restrictions>
        <DenyNavigationOnIncomplete presentation="ALWAYS" response="ALWAYS" />
      </Restrictions>
      <Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="2"/>
      <Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="3"/>
    </Testlet>

    <Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="4"/>
  </Units>
</Booklet>
