=== iqb-berlin/testcenter/definitions/vo_Booklet.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="vo_Booklet"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

<xs:include schemaLocation="vo_Common.xsd"/>

  <!-- ###################################################################-->
  <xs:complexType name="UnitType">
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="label" type="xs:string" use="required"/>
    <xs:attribute name="labelshort" type="xs:string"/>
    <xs:attribute name="alias" type="xs:string"/>
  </xs:complexType>

  <!-- ###################################################################-->
  <xs:complexType name="TestletRestrictionsType">
    <xs:all>
      <xs:element name="TimeMax" type="ConfigType" minOccurs = "0" maxOccurs="1"/>
      <xs:element name="CodeToEnter" type="ConfigType" minOccurs = "0" maxOccurs="1"/>
      <xs:element name="Lock" type="ConfigType" minOccurs = "0" maxOccurs="1"/>
    </xs:all>
  </xs:complexType>

  <!-- ###################################################################-->
  <xs:group name="unitOrTestlet">
    <xs:choice>
      <xs:element name="Unit" type="UnitType" minOccurs = "1" maxOccurs="unbounded"/>
      <xs:element name="Testlet" type="TestletType" minOccurs = "1" maxOccurs="unbounded"/>
    </xs:choice>
  </xs:group>

  <!-- ###################################################################-->
  <xs:complexType name="TestletType">
    <xs:sequence>
      <xs:element name="Restrictions" type="TestletRestrictionsType" minOccurs="0" maxOccurs="1"/>
      <xs:choice>
        <xs:element name="Unit" type="UnitType" minOccurs = "1" maxOccurs="unbounded"/>
        <xs:group ref="unitOrTestlet" minOccurs = "1" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="label" type="xs:string" />
  </xs:complexType>

  <!-- ###################################################################-->
  <!-- ###################################################################-->

  <xs:element name="Booklet">
    <xs:complexType>
      <xs:all>
        <xs:element name="Metadata" type="MetadataType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="BookletConfig" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Config" type="KeyValueType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Units" type="TestletType" minOccurs="1" maxOccurs="1"/>
      </xs:all>
    </xs:complexType>
    <xs:unique name="BookletConfigKey">
      <xs:selector xpath="Config"/>
      <xs:field xpath="@key"/>
    </xs:unique>
  </xs:element>
</xs:schema>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_NavRestr_Testlet-2.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.4.0/definitions/vo_Booklet.xsd">
  <Metadata>
    <Id>CY-Bklt_NavRestrTslt-2</Id>
    <Label>test restriction parameter DenyNavigationOnIncomplete value-2</Label>
  </Metadata>

  <BookletConfig>

    <!--its only important to navigated to the next page if page navibuttons are disabled -->
    <Config key="pagingMode">buttons</Config>
    <Config key="force_presentation_complete">OFF</Config>
    <Config key="force_response_complete">OFF</Config>
  </BookletConfig>

  <Units>

    <Testlet id="Tslt1" label="Aufgabenblock">
      <Restrictions>
        <TimeMax minutes="2" leave = "confirm"/>
        <DenyNavigationOnIncomplete presentation="ON" response="ON" />
      </Restrictions>
      <Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="1"/>
      <Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="2"/>
    </Testlet>

    <Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="3"/>
  </Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_RestrictionNavValue-3.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.3.0/definitions/vo_Booklet.xsd">
  <Metadata>
    <Id>CY-Bklt_NavRestrVal3</Id>
    <Label>test restriction parameter DenyNavigationOnIncomplete value-3</Label>
  </Metadata>

  <BookletConfig>

    <!--its only important to navigated to the next page if page navibuttons are disabled -->
    <Config key="pagingMode">buttons</Config>
    <Config key="force_presentation_complete">ON</Config>
    <Config key="force_response_complete">ON</Config>
  </BookletConfig>

  <Units>

    <Testlet id="Tslt1" label="Aufgabenblock">
      <Restrictions>
        <TimeMax minutes="2" leave = "confirm"/>
        <DenyNavigationOnIncomplete presentation="ALWAYS" response="ALWAYS" />
      </Restrictions>
      <Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="1"/>
      <Unit id="CY-Unit.Sample-101" label="Aufgabe2" labelshort="2" alias="unit-2"/>
    </Testlet>

    <Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="3"/>
  </Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_Mode_RunHotReturn.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/15.5.0/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>runhotret</Id>
		<Label>Controller Mode: run-hot-return</Label>
		<Description>Test f√ºr den Modus run-hot-return</Description>
	</Metadata>

	<BookletConfig>
		<Config key="force_presentation_complete">ON</Config>
		<Config key="force_response_complete">ON</Config>
		<Config key="unit_show_time_left">ON</Config>
		<Config key="unit_menu">ON</Config>
    <Config key="unit_responses_buffer_time">20000000</Config>
    <Config key="unit_state_buffer_time">20000000</Config>
    <Config key="test_state_buffer_time">20000000</Config>
	</BookletConfig>

	<Units>
		<Unit id="UNIT.SAMPLE-100" label="Startseite" labelshort="1" />

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
				<CodeToEnter code="Hase">Bitte gib das Freigabewort ein.</CodeToEnter>
				<TimeMax minutes="1"/>
			</Restrictions>
			<Unit id="UNIT.SAMPLE-101" label="Aufgabe1" labelshort="2"/>
			<Unit id="UNIT.SAMPLE-102" label="Aufgabe2" labelshort="3"/>
			<Unit id="UNIT.SAMPLE-103" label="Aufgabe3" labelshort="4"/>
		</Testlet>

		<Unit id="UNIT.SAMPLE-104" label="Endseite" labelshort="5"/>
	</Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_Config_value-2.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.0.0/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>CY-BkltConfigValue-2</Id>
		<Label>Test Bklt Configs value-2</Label>
		<Description>Testen der zweiten Werte</Description>
	</Metadata>

	<BookletConfig>

		<!--its only important to navigated to the next page if page navibuttons are disabled -->
		<Config key="pagingMode">buttons</Config>

		<Config key="unit_navibuttons">ARROWS_ONLY</Config>
		<Config key="force_presentation_complete">ALWAYS</Config>
		<Config key="force_response_complete">ALWAYS</Config>
		<Config key="allow_player_to_terminate_test">LAST_UNIT</Config>
		<Config key="unit_screenheader">WITH_BOOKLET_TITLE</Config>
		
	</BookletConfig>

	<Units>

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
        <TimeMax minutes="2" leave = "confirm"/>
			</Restrictions>
				<Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="1"/>
        <Unit id="CY-Unit.Sample-101" label="Aufgabe2" labelshort="2" alias="cpy"/>
		</Testlet>
	</Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_TimeRestriction.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.1.0/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>CY-Bklt_TimeRestr</Id>
		<Label>Time Restrictions</Label>
		<Description></Description>
	</Metadata>

	<BookletConfig>
		<Config key="force_presentation_complete">OFF</Config>
		<Config key="force_response_complete">OFF</Config>
		<Config key="unit_show_time_left">ON</Config>
		<Config key="unit_menu">ON</Config>
		<Config key="lock_test_on_termination">ON</Config>
	</BookletConfig>

	<Units>
		<Unit id="CY-Unit.Sample-100" label="Startseite" labelshort="1" />

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
				<CodeToEnter code="Hase">Bitte gib das Freigabewort ein.</CodeToEnter>
				<TimeMax minutes="0.2"/>
			</Restrictions>
			<Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="2"/>
			<Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="3"/>
			<Unit id="CY-Unit.Sample-103" label="Aufgabe3" labelshort="4"/>
		</Testlet>
		
		<Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="5"/>
	</Units>
</Booklet>

=== iqb-berlin/testcenter/sampledata/system-test/CY_BKL_Config_value-3.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.0.0/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>CY-BkltConfigValue-3</Id>
		<Label>Test Bklt Configs value-3</Label>
		<Description>Testen der dritten Werte</Description>
	</Metadata>

	<BookletConfig>

		<!--its only important to navigated to the next page if page navibuttons are disabled -->
		<Config key="pagingMode">buttons</Config>
		
		<Config key="page_navibuttons">OFF</Config>
		<Config key="unit_menu">FULL</Config>
		<Config key="unit_navibuttons">FORWARD_ONLY</Config>
		<Config key="force_presentation_complete">ALLWAYS</Config>
		<Config key="force_response_complete">ALLWAYS</Config>
		<Config key="unit_show_time_left">ON</Config>
		<Config key="unit_time_left_warnings">1</Config>
		<Config key="show_end_button_in_player">ONLY_LAST_UNIT</Config>
		<Config key="restore_current_page_on_return">ON</Config>
		<Config key="allow_player_to_terminate_test">LAST_UNIT</Config>
		<Config key="lock_test_on_termination">ON</Config>
		<Config key="ask_for_fullscreen">ON</Config>
		<Config key="show_fullscreen_button">ON</Config>
		<Config key="unit_screenheader">WITH_BLOCK_TITLE</Config>
		<Config key="unit_title">OFF</Config>
		

	</BookletConfig>

	<Units>

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
				<TimeMax minutes="2"/>
			</Restrictions>
			<Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="1"/>
			<Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="2"/>
		</Testlet>
		
		<Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="3"/>
	</Units>
</Booklet>
