=== iqb-berlin/testcenter/definitions/vo_Testtakers.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="vo_Testtakers" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Testtakers" >
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Metadata">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Description" type="xs:string" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="CustomTexts" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="CustomText" type="customTextType" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Profiles" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="GroupMonitor" minOccurs="0" type="ProfilesSectorGroupMonitorType" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Group" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="AssetAssignments" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Asset" type="AssetAssignmentType" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="GroupAssetAssignmentSlot">
                  <xs:selector xpath="Asset"/>
                  <xs:field xpath="@slot"/>
                </xs:unique>
              </xs:element>
              <xs:element name="Login" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:choice>
                      <xs:element name="Booklet" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="codes" type="xs:string" />
                              <xs:attribute name="state" type="StateListType" />
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="Profile" minOccurs="0" maxOccurs="unbounded" type="ProfileReferenceType" />
                    </xs:choice>
                    <xs:element name="AssetAssignments" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Asset" type="AssetAssignmentType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                      <xs:unique name="LoginAssetAssignmentSlot">
                        <xs:selector xpath="Asset"/>
                        <xs:field xpath="@slot"/>
                      </xs:unique>
                    </xs:element>
                    <xs:element name="ViewSettings" minOccurs="0">
                      <xs:complexType>
                        <xs:all>
                          <xs:element name="theme" type="xs:string" minOccurs="0"/>
                          <xs:element name="codeInput" minOccurs="0">
                            <xs:complexType>
                              <xs:all>
                                <xs:element name="type" minOccurs="1">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:enumeration value="text-field"/>
                                      <xs:enumeration value="keypad-symbols"/>
                                      <xs:enumeration value="keypad-symbols-alt"/>
                                      <xs:enumeration value="keypad-numbers"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="length" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                      <xs:minInclusive value="3"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                              </xs:all>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="monitorBookletVisibility"
                                      type="GroupMonitorBookletVisibilityType"
                                      minOccurs="0"/>
                        </xs:all>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="pw" type="xs:string"/>
                  <xs:attribute name="mode">
                    <xs:annotation>
                      <xs:documentation>
                        See: https://github.com/iqb-berlin/testcenter/blob/master/docs/pages/test-mode.md
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="run-hot-return">
                          <xs:annotation>
                            <xs:documentation>
                              Default. Execute the test with all restrictions set by booklet definition. If the
                              test execution stops for any reason and the login is used again, return to the former
                              state: Restore the responses and and continue execution.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="run-hot-restart">
                          <xs:annotation>
                            <xs:documentation>
                              Execute the test with all restrictions set by booklet definition. If the
                              test execution stops for any reason and the login is used again, assume another testee:
                              Ignore all former states and restart the test.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="run-trial">
                          <xs:annotation>
                            <xs:documentation>
                              Execute the test with most of the restrictions set by booklet definition,
                              store responses
                            </xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="run-review">
                          <xs:annotation>
                            <xs:documentation>
                              Execute the test with no restrictions, do not save responses permanently,
                              allow review comments for the test in general and every unit
                            </xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="monitor-group">
                          <xs:annotation>
                            <xs:documentation>
                              Monitor of test execution: For the group.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="monitor-study">
                          <xs:annotation>
                            <xs:documentation>
                              This role can monitor all group of the study (= all groups in this workspace).
                              More functionality will follow.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="sys-check-login">
                          <xs:annotation>
                            <xs:documentation>
                              If this role is given once within a testcenter instance, the system check will be removed
                              from the login-page and can only be accessed after logging into the workspace where this
                              role exists.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="run-demo">
                          <xs:annotation>
                            <xs:documentation>
                              Execute the test with no restrictions, do not save responses permanently,
                              don't allow review comments for the test in general and every unit
                            </xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="run-simulation">
                          <xs:annotation>
                            <xs:documentation>
                              Execute the test with all restrictions, but don't save response data.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="monitorcode" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>
                        This attribute creates a group-monitor for this group which has the same login-credentials as
                        the testees, but its own code.
                        ** This feature is only a proposal and not implemented **
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="label" type="xs:string" use="required"/>
            <xs:attribute name="validTo">
              <xs:annotation>
                <xs:documentation>
                  Login-/Person-Token of this group are valid until the specified date and can not be created after.
                  Provide the date in the format `dd/mm/yyyy hh:mm`.
                  If omitted, they are valid forever or, if provided, until `validFor` is reached.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="\d{1,2}/\d{1,2}/\d{2,4}\W\d{1,2}:\d{2}" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="validFrom">
              <xs:annotation>
                <xs:documentation>
                  If provided, Login-/Person-Token are only valid and can only be created *after* this date.
                  Provide the date in the format `dd/mm/yyyy hh:mm`.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="\d{1,2}/\d{1,2}/\d{2,4}\W\d{1,2}:\d{2}" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="validFor" type="xs:integer">
              <xs:annotation>
                <xs:documentation>
                  Login-/Person-Token of this group are valid for the specified timespan (in minutes)
                  after their creation.
                  If omitted, they are valid forever or, if provided until `validTo` is reached.
                  If both is provided, `validFor` and `validTo`, the Login-/Person-Token is valid to whatever comes
                  first, the specified moment of `validTo` or the expiration of `validFor` minutes.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="TesttakerLogin">
      <xs:selector xpath="Group/Login"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="CustomTextKey">
      <xs:selector xpath="CustomTexts/CustomText"/>
      <xs:field xpath="@key"/>
    </xs:unique>
    <xs:unique name="GroupId">
      <xs:selector xpath="Group"/>
      <xs:field xpath="@id"/>
    </xs:unique>
    <xs:key name="profileId">
      <xs:selector xpath="Profiles/*/Profile"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="profileIdRef" refer="profileId">
      <xs:selector xpath="Group/Login/Profile" />
      <xs:field xpath="@id"/>
    </xs:keyref>
  </xs:element>

  <xs:complexType name="customTextType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="key" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="AssetAssignmentType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="slot" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="StateListType">
    <xs:restriction base="xs:string">
      <xs:pattern value="([a-z\d-]+:[a-z\d-]+,?\W?)+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ProfileReferenceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="id" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="ProfileType">
    <xs:sequence>
      <xs:element name="Filter" type="FilterType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="label" type="xs:string" />
    <xs:attribute name="blockColumn" type="GroupMonitorProfileColumnSetting" />
    <xs:attribute name="unitColumn" type="GroupMonitorProfileColumnSetting" />
    <xs:attribute name="groupColumn" type="GroupMonitorProfileColumnSetting" />
    <xs:attribute name="bookletColumn" type="GroupMonitorProfileColumnSetting" />
    <xs:attribute name="bookletStatesColumns" type="xs:string" />
    <xs:attribute name="view" type="GroupMonitorProfileViewSetting" />
    <xs:attribute name="filterPending" type="GroupMonitorProfileFilterSetting" />
    <xs:attribute name="filterLocked" type="GroupMonitorProfileFilterSetting" />
    <xs:attribute name="autoselectNextBlock" type="GroupMonitorProfileFilterSetting" />
  </xs:complexType>

  <xs:complexType name="FilterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="field" type="GroupMonitorProfileFilterField" />
        <xs:attribute name="type" type="FilterTypeType" />
        <xs:attribute name="value" type="xs:string" />
        <xs:attribute name="subValue" type="xs:string" />
        <xs:attribute name="not" type="xs:boolean" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="FilterTypeType" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="equal" />
      <xs:enumeration value="substring" />
      <xs:enumeration value="regex" />
    </xs:restriction>
  </xs:simpleType>

  <!-- see groupMonitorInterfaces.ts -->
  <xs:simpleType name="GroupMonitorProfileFilterField">
    <xs:restriction base="xs:string">
      <xs:enumeration value="bookletLabel"/>
      <xs:enumeration value="personLabel"/>
      <xs:enumeration value="state"/>
      <xs:enumeration value="blockLabel"/>
      <xs:enumeration value="groupName"/>
      <xs:enumeration value="bookletId"/>
      <xs:enumeration value="unitId"/>
      <xs:enumeration value="unitLabel"/>
      <xs:enumeration value="blockId"/>
      <xs:enumeration value="testState"/>
      <xs:enumeration value="mode"/>
      <xs:enumeration value="bookletSpecies"/>
      <xs:enumeration value="bookletStates"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="GroupMonitorProfileColumnSetting">
    <xs:restriction base="xs:string">
      <xs:enumeration value="show"/>
      <xs:enumeration value="hide"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="GroupMonitorProfileFilterSetting">
    <xs:restriction base="xs:string">
      <xs:enumeration value="yes"/>
      <xs:enumeration value="no"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="GroupMonitorProfileViewSetting">
    <xs:restriction base="xs:string">
      <xs:enumeration value="full"/>
      <xs:enumeration value="medium"/>
      <xs:enumeration value="small"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="GroupMonitorBookletVisibilityType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="visible"/>
      <xs:enumeration value="collapsed"/>
      <xs:enumeration value="hidden"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ProfilesSectorGroupMonitorType">
    <xs:sequence>
      <xs:element name="Profile" minOccurs="0" maxOccurs="unbounded" type="ProfileType" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== iqb-berlin/testcenter/sampledata/system-test/CY_Test_Logins.xml
<?xml version="1.0" encoding="utf-8"?>
<Testtakers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.0.0/definitions/vo_Testtakers.xsd">

  <Metadata>
    <Description>Logins f√ºr die Cypress Controller-Tests</Description>
  </Metadata>

  <CustomTexts>
    <CustomText key="app_title">TEST TESTCENTER</CustomText>
  </CustomTexts>

  <Group id="rundemo" label="RunDemo">
    <Login mode="run-demo" name="Test_Demo_Ctrl" pw="123">
      <Booklet>CY-Bklt_rundemo</Booklet>
    </Login>
  </Group>

  <Group id="runrev" label="RunReview">
    <Login mode="run-review" name="Test_Review_Ctrl" pw="123">
      <Booklet>CY-Bklt_runreview</Booklet>
    </Login>
  </Group>

  <Group id="runhotret" label="RunHotReturn">
    <Login mode="run-hot-return" name="Test_HotReturn_Ctrl1" pw="123">
      <Booklet>CY-Bklt_runhotret</Booklet>
    </Login>
    <Login mode="run-hot-return" name="Test_HotReturn_Ctrl2" pw="123">
      <Booklet>CY-Bklt_runhotret</Booklet>
    </Login>
    <Login mode="run-hot-return" name="Test_HotReturn_Ctrl3" pw="123">
      <Booklet>CY-Bklt_runhotret</Booklet>
    </Login>
    <Login mode="run-hot-return" name="Test_HotReturn_Ctrl4" pw="123">
      <Booklet>CY-Bklt_runhotret</Booklet>
    </Login>
  </Group>

  <Group id="runhotres" label="RunHotRestart">
    <Login mode="run-hot-restart" name="Test_HotRestart_Ctrl1" pw="123">
      <Booklet>CY-Bklt_runhotres</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="Test_HotRestart_Ctrl2" pw="123">
      <Booklet>CY-Bklt_runhotres</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="Test_HotRestart_Ctrl3" pw="123">
      <Booklet>CY-Bklt_runhotres</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="Test_HotRestart_Ctrl4" pw="123">
      <Booklet>CY-Bklt_runhotres</Booklet>
    </Login>
  </Group>

  <Group id="SM_LoginPossibilities" label="Sessionmanagement Login Possibilities">
    <Login mode="run-demo" name="without_pw" pw="">
      <Booklet>CY-Bklt_rundemo</Booklet>
    </Login>
    <Login mode="run-demo" name="with_pw" pw="101">
      <Booklet>CY-Bklt_rundemo</Booklet>
    </Login>
    <Login mode="run-demo" name="as_link">
      <Booklet>CY-Bklt_rundemo</Booklet>
      <Booklet>CY-Bklt_SM</Booklet>
    </Login>
    <Login mode="run-demo" name="as_link_immediate">
      <Booklet>CY-Bklt_rundemo</Booklet>
    </Login>
    <Login mode="run-demo" name="as_code1" pw="102">
      <Booklet codes="as_code01">CY-Bklt_rundemo</Booklet>
    </Login>
    <Login mode="run-demo" name="as_code2">
      <Booklet codes="as_code02">CY-Bklt_rundemo</Booklet>
    </Login>
  </Group>


  <Group id="SM_HotModes" label="SessionManagement Hot-Modes-Test Logins">
    <Login mode="run-hot-return" name="hret1" pw="201">
      <Booklet>CY-Bklt_SM</Booklet>
    </Login>
    <Login mode="run-hot-return" name="hret2" pw="202">
      <Booklet>CY-Bklt_SM</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="hres1" pw="203">
      <Booklet>CY-Bklt_SM</Booklet>
    </Login>
    <Login mode="monitor-group" name="group-monitor" pw="301"/>
    <Login mode="monitor-study" name="tsm" pw="401"/>
  </Group>

  <Group id="SM_ValidFromLogin" validFrom="1/6/2023 10:00" label="SessionManagement valid from login">
    <Login mode="run-demo" name="validFrom01" pw="123">
      <Booklet>CY-Bklt_rundemo</Booklet>
    </Login>
  </Group>

  <Group id="SM_ValidToLogin" validTo="1/6/2023 10:00" label="SessionManagement valid to login">
    <Login mode="run-demo" name="validTo01" pw="123">
      <Booklet>CY-Bklt_rundemo</Booklet>
    </Login>
  </Group>

  <Group id="SM_ValidForLogin" validFor="10" label="SessionManagement valid for login">
    <Login mode="run-review" name="validFor01" pw="123">
      <Booklet>CY-Bklt_runreview</Booklet>
    </Login>
  </Group>

  <Group id="SM_syscheck" label="SessionManagement Sys-Check">
    <Login mode="sys-check-login" name="syscheck"/>
  </Group>

  <Group id="bookletConfig" label="booklet config parameter check">
    <Login mode="run-hot-restart" name="bklConfigDefault" pw="123">
      <Booklet>CY-BkltConfigDefaults</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="bklConfigValue1" pw="123">
      <Booklet>CY-BkltConfigValue-1</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="bklConfigValue2" pw="123">
      <Booklet>CY-BkltConfigValue-2</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="bklConfigValue3" pw="123">
      <Booklet>CY-BkltConfigValue-3</Booklet>
    </Login>
  </Group>

  <Group id="testletRestrictions" label="testlet restriction parameter check">
    <Login mode="run-hot-return" name="TimeRestr_HotRet1" pw="123">
      <Booklet>CY-Bklt_TimeRestr</Booklet>
    </Login>
    <Login mode="run-hot-return" name="TimeRestr_HotRet2" pw="123">
      <Booklet>CY-Bklt_TimeRestr</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="TimeRestr_HotRes1" pw="123">
      <Booklet>CY-Bklt_TimeRestr</Booklet>
    </Login>
    <Login mode="run-demo" name="TimeRestr_Demo1" pw="123">
      <Booklet>CY-Bklt_TimeRestr</Booklet>
    </Login>
    <Login mode="run-review" name="TimeRestr_Review1" pw="123">
      <Booklet>CY-Bklt_TimeRestr</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="LeaveVal1" pw="123">
      <Booklet>CY-Bklt_LeaveVal1</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="LeaveVal2" pw="123">
      <Booklet>CY-Bklt_LeaveVal2</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="LeaveVal3" pw="123">
      <Booklet>CY-Bklt_LeaveVal3</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="NavRestrVal1" pw="123">
      <Booklet>CY-Bklt_NavRestrVal1</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="NavRestrVal2" pw="123">
      <Booklet>CY-Bklt_NavRestrVal2</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="NavRestrVal3" pw="123">
      <Booklet>CY-Bklt_NavRestrVal3</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="RestrLockAfterLeave1" pw="123">
      <Booklet>CY-Bklt_LockAfterLeave-1</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="RestrLockAfterLeave2" pw="123">
      <Booklet>CY-Bklt_LockAfterLeave-2</Booklet>
    </Login>
  </Group>

</Testtakers>

=== iqb-berlin/testcenter/sampledata/system-test/groupmon/CY_Logins_GM.xml
<?xml version="1.0" encoding="utf-8"?>
<Testtakers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/18.0.0-beta2/definitions/vo_Testtakers.xsd">

  <Metadata>
    <Description>Logins für Cypress Test: Groupmonitor</Description>
  </Metadata>

  <Profiles>
    <GroupMonitor>
      <Profile
        id="small"
        label="Superklein"
        blockColumn="hide"
        unitColumn="hide"
        groupColumn="hide"
        bookletColumn="hide"
        bookletStatesColumns=""
        view="small"
        filterLocked="yes"
        filterPending="yes"
      >
        <Filter label="Reduced Booklet" type="equal" field="bookletLabel" value="Reduced Booklet" />
      </Profile>
      <Profile
        id="all"
        label="Alles zeigen"
        blockColumn="show"
        unitColumn="show"
        groupColumn="show"
        bookletColumn="show"
        bookletStatesColumns="level bonus"
        view="full"
        filterLocked="no"
        filterPending="no"
        autoselectNextBlock="no"
      >
      </Profile>
    </GroupMonitor>
  </Profiles>

  <Group id="filter-profiles" label="Filter-Profiles">

    <Login mode="run-hot-return" name="testtaker-a" pw="123">
      <Booklet>Cy-Bklt_GM-1</Booklet>
    </Login>

    <Login mode="monitor-group" name="GM-1" pw="">
      <Profile id="all" />
      <Profile id="small" />
    </Login>
  </Group>

</Testtakers>

=== iqb-berlin/testcenter/sampledata/system-test/session-management/CY_Logins_SM.xml
<?xml version="1.0" encoding="utf-8"?>
<Testtakers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/18.0.0-beta2/definitions/vo_Testtakers.xsd">

  <Metadata>
    <Description>Logins für Cypress Test: Session-Management</Description>
  </Metadata>

  <Group id="login-variants" label="Login-Variants">
    <Login mode="run-demo" name="SM-1" pw="">
      <Booklet>Cy-Bklt_SM-1</Booklet>
    </Login>
    <Login mode="run-demo" name="SM-2" pw="101">
      <Booklet>Cy-Bklt_SM-1</Booklet>
    </Login>
    <Login mode="run-demo" name="SM-3">
      <Booklet>Cy-Bklt_SM-1</Booklet>
      <Booklet>Cy-Bklt_SM-2</Booklet>
    </Login>
    <Login mode="run-demo" name="SM-4">
      <Booklet>Cy-Bklt_SM-1</Booklet>
    </Login>
    <Login mode="run-demo" name="SM-5" pw="102">
      <Booklet codes="as_code01">Cy-Bklt_SM-1</Booklet>
    </Login>
    <Login mode="run-demo" name="SM-6">
      <Booklet codes="as_code02">Cy-Bklt_SM-1</Booklet>
    </Login>
  </Group>

  <Group id="valid-from-login" validFrom="1/6/2023 10:00" label="Valid-From-Login">
    <Login mode="run-hot-restart" name="SM-10" pw="123">
      <Booklet>Cy-Bklt_SM-1</Booklet>
    </Login>
  </Group>

  <Group id="valid-to-login" validTo="1/6/2023 10:00" label="Valid-To-Login">
    <Login mode="run-hot-restart" name="SM-11" pw="123">
      <Booklet>Cy-Bklt_SM-1</Booklet>
    </Login>
  </Group>

  <Group id="valid-for-login" validFor="10" label="Valid-For-Login">
    <Login mode="run-hot-return" name="SM-12" pw="123">
      <Booklet>Cy-Bklt_SM-1</Booklet>
    </Login>
  </Group>

  <Group id="hote-modes" label="Hote-Modes">
    <Login mode="run-hot-return" name="SM-7" pw="201">
      <Booklet>Cy-Bklt_SM-2</Booklet>
    </Login>
    <Login mode="run-hot-return" name="SM-8" pw="202">
      <Booklet>Cy-Bklt_SM-2</Booklet>
    </Login>
    <Login mode="run-hot-restart" name="SM-9" pw="203">
      <Booklet>Cy-Bklt_SM-2</Booklet>
    </Login>
  </Group>

</Testtakers>
