=== iqb-berlin/testcenter/definitions/vo_Unit.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="vo_Unit" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="Variable">
      <xs:sequence>
        <xs:element name="Values" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Value" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="complete" type="xs:boolean" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:ID" >
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type" type="VariableTypeValue" use="required"/>
      <xs:attribute name="format" type="VariableFormatValue"/>
      <xs:attribute name="multiple" type="xs:boolean"/>
      <xs:attribute name="nullable" type="xs:boolean"/>
  </xs:complexType>

  <xs:simpleType name="VariableTypeValue">
    <xs:restriction base="xs:string">
      <xs:enumeration value="string"/>
      <xs:enumeration value="integer"/>
      <xs:enumeration value="number"/>
      <xs:enumeration value="boolean"/>
      <xs:enumeration value="attachment"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VariableFormatValue">
    <xs:restriction base="xs:string">
      <xs:enumeration value="text-selection"/>
      <xs:enumeration value="image"/>
      <xs:enumeration value="capture-image"/>
      <xs:enumeration value="audio"/>
      <xs:enumeration value="ggb-file"/>
      <xs:enumeration value="non-negative"/>
    </xs:restriction>
  </xs:simpleType>

 <xs:simpleType name="DependencyTarget">
  <xs:restriction base="xs:string">
   <xs:enumeration value="player"/>
   <xs:enumeration value="editor"/>
   <xs:enumeration value="schemer"/>
   <xs:enumeration value="coder"/>
  </xs:restriction>
 </xs:simpleType>

  <xs:simpleType name="DependencyType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="service-url"/>
      <xs:enumeration value="filename"/>
    </xs:restriction>
  </xs:simpleType>

 <xs:complexType name="Dependency">
  <xs:simpleContent>
   <xs:extension base="xs:string">
    <xs:attribute name="target" type="DependencyTarget" use="required"/>
     <xs:attribute name="type" type="DependencyType" use="required"/>
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>

  <xs:element name="Unit" >
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Metadata">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" type="xs:ID" />
              <xs:element name="Label" type="xs:string" />
              <xs:element name="Description" type="xs:string" minOccurs="0" />
              <xs:element name="Lastchange" type="xs:dateTime" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:sequence>
          <xs:choice>
            <xs:element name="Definition">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attribute name="player" type="xs:string" use="required"/>
                    <xs:attribute name="editor" type="xs:string"/>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
            <xs:element name="DefinitionRef">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attribute name="player" type="xs:string" use="required"/>
                    <xs:attribute name="editor" type="xs:string"/>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:choice>
        </xs:sequence>

        <xs:element name="CodingSchemeRef" minOccurs="0">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="schemer" type="xs:string" use="required"/>
                <xs:attribute name="schemeType" type="xs:string"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>

        <xs:element name="Dependencies" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Dependency" type="Dependency" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="BaseVariables" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Variable" maxOccurs="unbounded" minOccurs="0" type="Variable" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="DerivedVariables" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Variable" maxOccurs="unbounded" minOccurs="0" type="Variable" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== iqb-berlin/testcenter/sampledata/aspect/testcenterTEST4.xml
<?xml version="1.0"?>
<Unit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/17.4.1/definitions/vo_Unit.xsd">
  <Metadata lastChange="2026-05-29T10:59:33.475Z">
    <Id>testcenterTEST4</Id>
    <Label>tct4</Label>
    <Reference/>
  </Metadata>
  <DefinitionRef player="iqb-player-aspect@2.12" editor="iqb-editor-aspect@2.12" lastChange="2026-05-29T10:59:40.390Z">testcenterTEST4.voud</DefinitionRef>
  <BaseVariables>
    <Variable id="text_1780052375345_1" alias="text_1" type="no-value" format="" nullable="false" multiple="false" page=""/>
  </BaseVariables>
</Unit>

=== iqb-berlin/testcenter/sampledata/system-test/CY_speedUnit1.xml
<?xml version="1.0"?>
<Unit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/16.0.1/definitions/vo_Unit.xsd">
  <Metadata lastChange="2025-07-10T08:25:46.805Z">
    <Id>CY-Speed.Unit-1</Id>
    <Label/>
    <Reference/>
  </Metadata>
  <DefinitionRef player="iqb-player-speedtest@3.0" editor="iqb-editor-speedtest@3.0" lastChange="2025-07-10T08:31:11.773Z">CY_speedUnit1.voud</DefinitionRef>
  <BaseVariables>
    <Variable id="value" alias="value" type="integer" format="" nullable="false" multiple="false"/>
    <Variable id="time" alias="time" type="integer" format="" nullable="false" multiple="false"/>
    <Variable id="activeQuestionIndex" alias="activeQuestionIndex" type="no-value" format="" nullable="false" multiple="false"/>
    <Variable id="total_correct" alias="total_correct" type="integer" format="" nullable="false" multiple="false"/>
    <Variable id="total_wrong" alias="total_wrong" type="integer" format="" nullable="false" multiple="false"/>
  </BaseVariables>
  <CodingSchemeRef schemer="" lastChange="2025-07-10T08:24:39.098Z"/>
</Unit>
